export interface OrderDTO{
    orderId?: number; // Optional since it's usually generated by backend
    userId: number;
    razorpayPaymentId: string;
    razorpayOrderId: string;
    razorpaySignature: string;
    username: string;
    email: string;
    mobileNumber: string;
    amount: string;
    profile: string; // Can be address or user profile string
    orderStatus: string;
}